version: '3.3'
services:
  mancala-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8099:8099"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_REDIS_HOST=redisdb
      - SPRING_REDIS_PORT=6379
    depends_on:
      - mongodb
      - redisdb
  mongodb:
    image: mongo:latest
    container_name: "mancala_mongodb"
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mancala_db
    volumes:
      - my_mancala:/data/db

  redisdb:
    restart: always
    container_name: "mancala_redis"
    image: redis:latest
    ports:
      - "6379:6379"
# Names our volume
volumes:
  my_mancala: