version: '3.3'
services:
  mongodb:
    image: mongo:latest
    container_name: "dzone_mancala_mongodb"
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mancala_db
    volumes:
      - my_mancala:/data/db
# Names our volume
volumes:
  my_mancala: