version: '3.3'
services:
  mongodb:
    image: mongo:latest
    container_name: "mancala_mongodb"
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mancala_db
    volumes:
      - my_mancala:/data/db

  redisdb:
    restart: always
    container_name: "mancala_redis"
    image: redis:latest
    ports:
      - "6379:6379"
# Names our volume
volumes:
  my_mancala: